"""Shared configuration for NovelForge notebooks and apps."""

GENRE_VOCABULARY = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Fantasy",
    "Romance",
    "School Life",
    "Slice of Life",
    "Supernatural",
    "Mystery",
    "Psychological",
    "Horror",
    "Historical",
    "Sci Fi",
    "Sports",
    "Martial Arts",
    "Magic",
    "Isekai",
    "Harem",
    "Mecha",
    "Demons",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Josei",
    "BL",
    "GL",
    "Yaoi",
    "Yuri",
    "Shounen-ai",
    "Shoujo-ai",
    "Smut",
    "Wuxia",
    "Xianxia",
]


ENRICHED_GENRE_VOCABULARY = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Fantasy",
    "Romance",
    "BL/GL Romance",
    "Adult",
    "School Life",
    "Slice of Life",
    "Supernatural",
    "Mystery",
    "Psychological",
    "Horror",
    "Historical",
    "Sci Fi",
    "Sports",
    "Martial Arts",
    "Magic",
    "Isekai",
    "Harem",
    "Mecha",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Josei",
]


ENRICHED_LABEL_MAPPING = {
    "action": "Action",
    "adventure": "Adventure",
    "comedy": "Comedy",
    "drama": "Drama",
    "fantasy": "Fantasy",
    "romance": "Romance",
    "school": "School Life",
    "school life": "School Life",
    "slice of life": "Slice of Life",
    "supernatural": "Supernatural",
    "super power": "Supernatural",
    "demons": "Supernatural",
    "vampire": "Supernatural",
    "mythology": "Supernatural",
    "mystery": "Mystery",
    "suspense": "Mystery",
    "detective": "Mystery",
    "psychological": "Psychological",
    "horror": "Horror",
    "gore": "Horror",
    "historical": "Historical",
    "sci fi": "Sci Fi",
    "sci-fi": "Sci Fi",
    "space": "Sci Fi",
    "time travel": "Sci Fi",
    "sports": "Sports",
    "team sports": "Sports",
    "martial arts": "Martial Arts",
    "samurai": "Martial Arts",
    "wuxia": "Martial Arts",
    "magic": "Magic",
    "mahou shoujo": "Magic",
    "isekai": "Isekai",
    "reincarnation": "Isekai",
    "villainess": "Isekai",
    "xianxia": "Isekai",
    "harem": "Harem",
    "mecha": "Mecha",
    "seinen": "Seinen",
    "shoujo": "Shoujo",
    "shounen": "Shounen",
    "josei": "Josei",
    "bl": "BL/GL Romance",
    "gl": "BL/GL Romance",
    "boys love": "BL/GL Romance",
    "girls love": "BL/GL Romance",
    "yaoi": "BL/GL Romance",
    "yuri": "BL/GL Romance",
    "shounen-ai": "BL/GL Romance",
    "shoujo-ai": "BL/GL Romance",
    "hentai": "Adult",
    "ecchi": "Adult",
    "erotica": "Adult",
    "smut": "Adult",
}
