"""Shared configuration for NovelForge notebooks and apps."""

GENRE_VOCABULARY = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Fantasy",
    "Romance",
    "School Life",
    "Slice of Life",
    "Supernatural",
    "Mystery",
    "Psychological",
    "Horror",
    "Historical",
    "Sci Fi",
    "Sports",
    "Martial Arts",
    "Magic",
    "Isekai",
    "Harem",
    "Mecha",
    "Demons",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Josei",
    "BL",
    "GL",
    "Yaoi",
    "Yuri",
    "Shounen-ai",
    "Shoujo-ai",
    "Smut",
    "Wuxia",
    "Xianxia",
]
